% @author Florian Pfaff pfaff@kit.edu
% @date 2016

startAtIndex=1;
numFrames=19999;
downSamplyBy=1;
% onBelt=squeeze(any(...
%     gt_x_y_vx_vy(1,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)>beltBordersX(1) ...
%     & gt_x_y_vx_vy(1,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)<beltBordersX(2)&...
%     gt_x_y_vx_vy(2,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)>beltBordersY(1) & ...
%     gt_x_y_vx_vy(2,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)<beltBordersY(2)...
%     ,2));
%%

currentlyOnBelt=squeeze(gt_x_y_vx_vy(1,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)>beltBordersX(1) ...
    & gt_x_y_vx_vy(1,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)<beltBordersX(2)&...
    gt_x_y_vx_vy(2,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)>beltBordersY(1) & ...
    gt_x_y_vx_vy(2,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)<beltBordersY(2));
meanTimesOnBelt=mean(sum(currentlyOnBelt,1))
currentlyInPredictionPhase=squeeze(gt_x_y_vx_vy(1,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)>predictionEdgePosition ...
    & gt_x_y_vx_vy(1,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)<airbarPosition&...
    gt_x_y_vx_vy(2,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)>beltBordersY(1) & ...
    gt_x_y_vx_vy(2,startAtIndex:downSamplyBy:startAtIndex+numFrames-1,:)<beltBordersY(2));
meanTimesInPred=mean(sum(currentlyInPredictionPhase,1))
medianTimesInPred=median(sum(currentlyInPredictionPhase,1))